#Gasch data figure command line
#./genClusterAttrib -l ../../../results/networkinference/pgpm/gasch_segalexp/randinit1/r2_p-5_h0.6/model1/fold0/goproc_chip_allexpr_module.txt -o temp -c ../../../results/networkinference/pgpm/gasch_segalexp/randinit1/r2_p-5_h0.6/model1/fold0/chipenr_details.txt -g ../../../results/networkinference/pgpm/gasch_segalexp/randinit1/r2_p-5_h0.6/model1/fold0/goproc_details.txt -r ../../../results/networkinference/pgpm/gasch_segalexp/randinit1/r2_p-5_h0.6/model1/fold0/module_allreginfenr_details.txt -h ../../../projects/regnet_inf/group_lasso/segal_module_net/headers.txt -e ../../../projects/regnet_inf/group_lasso/segal_module_net/yeast_expr_redo_1.00miss.geneexp -m ../../../results/networkinference/pgpm/gasch_segalexp/randinit1/r2_p-5_h0.6/model1/fold0/modules.txt
DIR=../../../results/networkinference/pgpm/gasch_segalexp/separatefolds_redo/randinit1/r4_p-5_h0.6/part0/model1/fold0/
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattibs_v2 -c $DIR/chipenr_details.txt -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h ../../../data/expression/gaschstress/headernames_nospc.txt -e ../../../projects/regnet_inf/group_lasso/segal_module_net/yeast_expr_redo_1.00miss.geneexp -m $DIR/modules_highconf.txt -d $DIR/motifenr_details.txt"
DIR=../../../results/networkinference/pgpm/humanES/zeromean_withsignaling/randinit1/r4_p-5_h0.6/model1/fold0
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs -c $DIR/module_chipenr_details.txt -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h ../../../data/ron_ning_hes/processed/zeromean_headers.txt -e ../../../data/ron_ning_hes/processed/allzeromean_rmallzeros_1fc.geneexp -m $DIR/modules_highconf.txt -d $DIR/module_dnaseenr_proc4_details.txt"
DIR=example
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs -c $DIR/module_chipenr_details.txt -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h $DIR/zeromean_headers.txt -e $DIR/allzeromean_rmallzeros_1fc.geneexp -m $DIR/modules_highconf.txt -d $DIR/module_dnaseenr_proc4_details.txt"

DIR=~/results/networkinference/pgpm/mouse_f2/liver/randpartitions/part3/model1/fold0/
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h ~/projects/mouse_attie_dave_coon/f2/withprotein_liver_geneexp/randpartitions/liver/dataset3_headers.txt  -e ~/projects/mouse_attie_dave_coon/f2/withprotein_liver_geneexp/randpartitions/liver/dataset3_commonnames.txt  -m $DIR/modules_highconf_c0.6.txt -d $DIR/module_msigdb_jaspar_motifenr_details.txt"

DIR=~/results/networkinference/pgpm/influenza/include_proteinexp_regulators/mRNA_levels_of_reg/randinit1/model1/fold0/
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h ~/data/influenza/geneexp/mergedheaders_withprot_virulence_ordered.txt  -e ~/data/influenza/geneprot/analysis_jun22/allmouse_geneexp_withprot_1.00miss.geneexp  -m $DIR/modules.txt -d $DIR/module_msigdb_jaspar_motifenr_details.txt"
DIR=~/results/networkinference/pgpm/influenza/include_proteinexp_regulators/protein_levels_of_reg/randinit1/model1/fold0/
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h ~/data/influenza/geneexp/mergedheaders_withprot_virulence_ordered.txt  -e ~/data/influenza/geneprot/analysis_aug9/mRNA_1.7foldc_prot_0.50miss.txt -m $DIR/modules.txt -d $DIR/module_msigdb_jaspar_motifenr_details.txt"
DIR=~/results/networkinference/pgpm/influenza/mouse_include_nonreg_influenza_d45/part0/model1/fold0/
#mkdir $DIR/clusterattribs
#echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_details.txt -r $DIR/module_reginfenr_details.txt -h ~/data/influenza/geneexp/analysis_mar14/mergedheaders_reordered_virulence.txt  -e ~/data/influenza/geneexp/analysis_mar14/reordered_virulence_withheaders.txt -m $DIR/modules_c0.3.txt -d $DIR/module_msigdb_jaspar_motifenr_details.txt"
DIR=~/results/networkinference/pgpm/influenza/mouse_include_nonreg_influenza_d45/hierarchical_postproc/h0.5sim
mkdir $DIR/clusterattribs
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_msigdb_details.txt -r $DIR/module_reginfenr_details.txt -h ~/data/influenza/geneexp/analysis_mar14/mergedheaders_reordered_virulence.txt  -e ~/data/influenza/human_mouse_geneset/include_nonreg_union/human_mouse_diffexp_expfiltered_mouseexp_withheader.txt -m $DIR/clusterassign.txt -c $DIR/module_msigdb_motifenr_details.txt -d $DIR/screenenr_details.txt"

#DIR=~/results/networkinference/pgpm/influenza/human_include_nonreg_influenza_d45/part0/model1/fold0/
#echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_msigdb_details.txt -r $DIR/modulereginfenr_details.txt -h ~/data/influenza/human/allheaders.txt  -e ~/data/influenza/human_mouse_geneset/include_nonreg_union/human_mouse_diffexp_expfiltered_humanexp_withheader.txt -m $DIR/modules_c0.3.txt -d $DIR/msigdb_motifenr_details.txt"
DIR=~/results/networkinference/pgpm/influenza/human_include_nonreg_influenza_d45/hierarchical_postproc/h0.5sim
mkdir $DIR/clusterattribs
echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goproc_msigdb_details.txt -r $DIR/modulereginfenr_details.txt -h ~/data/influenza/human/allheaders.txt  -e ~/data/influenza/human_mouse_geneset/include_nonreg_union/human_mouse_diffexp_expfiltered_humanexp_withheader.txt -m $DIR/clusterassign.txt -c $DIR/msigdb_motifenr_details.txt -d $DIR/screenenr_details.txt"
#DIR=~/results/networkinference/pgpm/plants/plant_EL_JM/part4/model1/fold0/
#mkdir $DIR/clusterattribs
#echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goenr_details.txt -r $DIR/modulereginfenr_details.txt -h ~/data/plant/processed/TMM_header_grouporder.txt  -e ~/data/plant/jean-michel_doug_combined/EL_JMnew_intersect_ELexp.txt -m $DIR/modules_c0.3.txt -d $DIR/motifenr_details.txt"
#echo "./genClusterAttrib -l $DIR/goproc_chip_expr_module.txt -o $DIR/clusterattribs  -g $DIR/goenr_details.txt -r $DIR/modulereginfenr_details.txt -h ~/data/plant/jean-michel_doug_combined/ELJM_headers.txt  -e ~/data/plant/jean-michel_doug_combined/EL_JMnew_intersect_ELJMexp.txt -m $DIR/modules_c0.3.txt -d $DIR/motifenr_details.txt"
